### PR TITLE
Manage 'action:agent' message

### PR DESCRIPTION
**Pull request by lrocher**
Hi,

I propose you same changes include in [CodeConnectFix](https://github.com/lrocher/CodeConnectFix) for manage new agent message protocol use by [minecraft.makecode](https://minecraft.makecode.com/) for communicate with last Minecraft Bedrock version.

I have try to update index.d.ts and mitm.js files in consequence.

Regards

### CODE REVIEW

**Comment by XeroAlpha** [comment]
Sorry for replying you so late. Thank you for your contribution.

I tested it in 1.19.70.23 (version=17039360). `action:agent` request will respond by a command response and an agent action response. Is agent action response always right after the command response? Maybe it is possible to provide them all to the callback.

**Comment by lrocher** [comment]
Sorry for the delay too :)

In fact, it's depend of the command.
CommandAgent type message is use in newest communication protocol use by Minecraft MakeCode.
With this protocol, all command are send via CommandAgent message.
Basic command like 'surmon','fill', ..., only have only a commandResponse.
Specific Agent command like 'agent move' have a commandResponse and a commandAgentResponse.
I suppose commandResponse  is sent when action start and commandAgentResponse when action finish.


As an exemple, a chat message tp agent and move agent forward for 5 blocks.
<- [2] event: PlayerMessage
-> [2] command: 16 closechat
-> [2] command: 17 agent tp
<- [2] commandResponse: 16 0
<- [2] commandResponse: 17 0
-> [2] commandAgent: 18 agent move forward
<- [2] commandResponse: 18 0
<- [2] commandAgentResponse: 18 move
-> [2] commandAgent: 19 agent move forward
<- [2] commandResponse: 19 0
<- [2] commandAgentResponse: 19 move
-> [2] commandAgent: 20 agent move forward
<- [2] commandResponse: 20 0
<- [2] commandAgentResponse: 20 move
-> [2] commandAgent: 21 agent move forward
<- [2] commandResponse: 21 0
<- [2] commandAgentResponse: 21 move
-> [2] commandAgent: 22 agent move forward
<- [2] commandResponse: 22 0
<- [2] commandAgentResponse: 22 move

But, surmon 2 zombies don't have commandAgentResponse only commandResponse.

<- [2] event: PlayerMessage
-> [2] commandAgent: 26 closechat
-> [2] commandAgent: 27 summon zombie ~10 ~1 ~
<- [2] commandResponse: 26 0
<- [2] commandResponse: 27 0
-> [2] commandAgent: 28 summon zombie ~10 ~1 ~
<- [2] commandResponse: 28 0

**Comment by XeroAlpha** [comment]
By now, I'm working to rewrite the whole library with typescript. Last month, I found that BDS has also implemented this protocol, which means we can know the protocol detail by decompiling and debugging BDS.

As far as I know, there are 10 types of request:
- commandRequest
- subscribe
- unsubscribe
- action:agent
- chat:subscribe
- chat:unsubscribe
- data:block
- data:item
- data:mob
- ws:encrypt

And there are 8 types of response:
- commandResponse
- event
- chat
- action:agent
- data
- event
- ws:encrypt
- error

The whole library needs refactoring, so I decided to rewrite it as well.

-----
### A short guide about how to use wsserver in BDS:

Simply hook `?isEduMode@DedicatedServer@@EEBA_NXZ` in BDS and let it always returns true. So that you will find 4 education-exclusive commands appear, including `dedicatedwsserver`, which has the same syntax of `wsserver`.

**Comment by XeroAlpha** [comment]
mcpews 4.0 is fully rewritten with typescript, and has the functionality mentioned above. This pull request is no longer possible and necessary to merge. Thank you for your contribution.

**Pull request closed without merging**
